robot_description: "robot urdf description here"
robot_description_semantic: "robot srdf description here"
robot_planning_pipeline: "ompl"
robot_planning_plugin: "ompl_interface/OMPLPlanner"
robot_planning_adapters: "default_planner_request_adapters/AddTimeParameterization default_planner_request_adapters/FixWorkspaceBounds default_planner
